### ISSUE TITLE
SH server package.

### ISSUE THREAD

**Issue by john302** [venomlinux/scratchpkg#11]
I have SSH configured on my system, but I cannot find the package to install an SSH server. I have edited the sshd_config file to set it up, but I cannot find any packages with scratch search to install an SSH server. Is such a package offered by this distribution. scratch search openssh only returns the one I already have installed, but the server will not start.

**Comment by emmett1** [comment]
Maybe that package is not in the repo yet. Whats the package name? I could port it to Venom's repo.
Btw, you can run 'scratch locate filename>' to search file within ports even not installed.

**Comment by john302** [comment]
SSH server is running now, I guess after I edited the config file sshd_config it started working. Issue closed.
