### ISSUE TITLE
Why I'm seeing this

### ISSUE THREAD

**Issue by jolu-pa** [venomlinux/scratchpkg#18]
Hi!
I don't know why I'm seeing this on screen.
Any help?
`jolupa [ ~/pkg_sources/xorg/mesa ]$ sudo scratch sysup  
Checking for outdated packages...
sed: no es troba l'etiqueta per al salt a «exinfo»
Resolving dependencies...

[\e[0;32mu\e[0m] libarchive  [\e[0;36mn\e[0m] libxslt  [\e[0;36mn\e[0m] libxcb  [\e[0;32mu\e[0m] mesa  [\e[0;32mu\e[0m] rust  [\e[0;36mn\e[0m] polkit  [\e[0;32mu\e[0m] xorg-server `

I'm using XFCE4 Terminal
Thanks

**Comment by emmett1** [comment]
in which distro?

**Comment by jolu-pa** [comment]
I'm doing an LFS

**Comment by emmett1** [comment]
are you done with 'The Bash Shell Startup Files' on BLFS?

**Comment by jolu-pa** [comment]
Yep! Maybe I have to recheck but all is working perfectly... But I will recheck it just in case.

**Comment by emmett1** [comment]
hmmm...not sure why, since its used on your custom build linux distro, which i dont know how you set it up..

**Comment by jolu-pa** [comment]
I close this issue 'cause I can't find where's the problem because all seems right! 😅
