### ISSUE TITLE
ERROR: Package's database directory does not exist: /var/lib/scratchpkg/db

### ISSUE THREAD

**Issue by temp987349867934876** [venomlinux/scratchpkg#22]
I have /var/lib/scratchpkg/index

**Comment by temp987349867934876** [comment]
Have renamed /var/lib/scratchpkg/db.perms to db
after that I could install ...
Everything very odd.

**Comment by emmett1** [comment]
Please install latest release of venom linux, theres major changes to scratchpkg database.
