### ISSUE TITLE
SplitDebug and Install Sources

### ISSUE THREAD

**Issue by Spacefreak18** [venomlinux/scratchpkg#25]
I noticed that forking was disabled on this repo.

I have a somewhat working implementation of split debug and install sources working on my install that i wanted to commit to a fork.
[Split debug symbols on gentoo](https://wiki.gentoo.org/wiki/Debugging) (not to be confused with strip debug, i'm stripping the debug symbols and storing them separate from the executable)

I don't think it's ready for the main branch yet, and I was intending to test it organically on my system through normal use.

I just want to check it into git somewhere, anywhere.

**Comment by Spacefreak18** [comment]
`
--- /home/paul/git/scratchpkg/pkgbuild	2022-04-14 14:27:22.263601576 +0000
+++ /usr/bin/pkgbuild	2022-04-14 14:42:37.370297888 +0000
@@ -125,6 +125,7 @@
 pkg_unpack() {
 	SRC=$WORK_DIR/$name/src
 	PKG=$WORK_DIR/$name/pkg
+	SRC2=/usr/
 	
 	umask 022
 	
@@ -153,7 +154,11 @@
 		case $i in
 			*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tar.lz|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.zip|*.rpm)
 				msg "Unpacking: $i"
-				$TAR -p -o -C $SRC -xf $i;;
+				$TAR -p -o -C $SRC -xf $i
+				if [ "$INSTALL_SOURCES" = 1 ] || [ "$INSTALL_SOURCES" = "yes" ]; then
+					cp -r $SRC $SRC2;
+				fi
+				;;
 			*)
 				msg "Preparing: $i"
 				cp $i $SRC;;
@@ -162,7 +167,7 @@
 			msgerr "Unpacking/Preparing failed: $i"
 			abort 1
 		}
-	done	
+	done
 }
 
 pkg_build() {	
@@ -245,6 +250,25 @@
 	done
 }
 
+split_files() {	
+	if [ "$nostrip" ]; then
+		for i in $nostrip; do
+			xstrip="$xstrip -e $i"
+		done
+		FILTER="grep -v $xstrip"
+	else
+		FILTER="cat"
+	fi
+
+	mkdir -p /usr/debug/$name
+
+	DEBUGFILE="/usr/debug/$name/$name.debug"	
+
+	find . -type f -printf "%P\n" 2>/dev/null | $FILTER | while read -r binary ; do
+		${CROSS_COMPILE}strip --strip-all "$binary" -o $DEBUGFILE
+	done
+}
+
 compressinfomanpages() {
 	find . -type f -path "*/man/man*/*" | while read -r file; do
 		if [ "$file" = "${file%%.gz}" ]; then
@@ -298,6 +322,10 @@
 	if [ "$KEEP_DOC" = 0 ] || [ "$KEEP_DOC" = "no" ]; then
 		rm -fr usr/share/doc usr/share/gtk-doc usr/doc usr/gtk-doc
 	fi
+
+	if [ "$NO_SPLIT" = 0 ] || [ "$NO_SPLIT" = "no" ]; then
+		split_files
+	fi
 	
 	if [ "$NO_STRIP" = 0 ] || [ "$NO_STRIP" = "no" ]; then
 		strip_files
@@ -622,6 +650,8 @@
 WORK_DIR="/var/cache/scratchpkg/work"
 COMPRESSION_MODE="xz"
 NO_STRIP="no"
+NO_SPLIT="no"
+INSTALL_SOURCES="no"
 IGNORE_MDSUM="no"
 KEEP_LIBTOOL="no"
 KEEP_LOCALE="no"
`

**Comment by emmett1** [comment]
Wait, i dont think forking is disabled on this repo.

I would like to try out your implement of split debug and install features.

**Comment by Spacefreak18** [comment]
You're right.

I am terrible at using websites sometimes.

The reason I can't create a fork, is because i already did and I forgot about it! It doesn't make that obvious if you click the fork button again.
