### ISSUE TITLE
`scratch sysup -o` and `scratch sysup` may damage source package

### ISSUE THREAD

**Issue by Dieken** [venomlinux/scratchpkg#34]
Compiling source files is often very slow, I would like `scratch sysup` to parallely download source packages, 
so I run `scratch sysup -o` in the background, but sometimes `scratch sysup` will catch up and download
same file twice, that may damage the source package.

It would be better if there is a lock to prevent parallel downloads in `/usr/bin/pkgbuild`,  if a source package is
being downloaded, `scratch sysup` will wait but `scratch sysup -o` will just jump to next package.

**Comment by emmett1** [comment]
Hey. Yeah i aware of this issue. I just think that nobody wants to run 'scratch sysup' and 'scratch sysup -o' both at the same time.

I've been thinking about your idea to overcome this issue before but i put it on hold. Since you already point this, i might gonna have to find a way to do it.
