### ISSUE TITLE
Repos are down

### ISSUE THREAD

**Issue by voncloft** [venomlinux/scratchpkg#6]
Trying to sync get following error:

https://raw.githubusercontent.com/venomlinux/ports/8.4/core/
  Failed to download REPO: The requested URL returned error: 404 Not Found
Failed to get remote repo file
==> ERROR: Failed sync from https://raw.githubusercontent.com/venomlinux/ports/8.4/core

Tried going via web browser to address - says 404 not found, is it down?

**Comment by emmett1** [comment]
I never have repo called "8.4" in venom linux. I dont know how do you get
that. Are you running this on venom linux? Or you try to use scratchpkg on
your own distro?

**Comment by voncloft** [comment]
Scratchpkg on own distro

It worked for the past week.

I just did a git clone and ran ./INSTALL

**Comment by emmett1** [comment]
You can configure /etc/scratchpkg.repo to use repo from venom linux.
Check here for venom linux repo: https://github.com/venomlinux/ports/blob/master/core/scratchpkg/repo

**Comment by voncloft** [comment]
Thanks
