### ISSUE TITLE
build option does not fetch dependencies

### ISSUE THREAD

**Issue by cemkeylan** [venomlinux/scratchpkg#7]
Hi!
scratch does not install dependencies when you run with 'scratch build', but it installs dependencies when you run 'scratch install'

**Comment by emmett1** [comment]
Hi,
Yes, 'scratch build' does not install dependencies and 'scratch install' does.
I dont see why 'scratch build' need to install its dependencies. User can use 'scratch install' to install packages with all dependencies, while 'scratch build' intend to use when user need to debug some package build.

**Comment by cemkeylan** [comment]
Alright, that makes sense. Thanks for the clarification!

**Comment by emmett1** [comment]
No problem.
